//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreBoardApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScoreBoardDBEntities : DbContext
    {
        public ScoreBoardDBEntities()
            : base("name=ScoreBoardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UserIdentity> UserIdentities { get; set; }
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<plyerRankView> plyerRankViews { get; set; }
        public virtual DbSet<plyerBadmintonRankView> plyerBadmintonRankViews { get; set; }
        public virtual DbSet<plyerCarromRankView> plyerCarromRankViews { get; set; }
        public virtual DbSet<plyerChessRankView> plyerChessRankViews { get; set; }
        public virtual DbSet<plyerTTRankView> plyerTTRankViews { get; set; }
        public virtual DbSet<TeamRankView> TeamRankViews { get; set; }
    }
}
